// SPDX-License-Identifier: GPL-3.0-or-later
#include "managedsshconfig.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QRegularExpression>
#include <QSaveFile>
#include <QStandardPaths>

namespace Waypane
{
namespace
{
QString quoted(QString value)
{
    value.replace(QLatin1Char('\\'), QStringLiteral("\\\\"));
    value.replace(QLatin1Char('"'), QStringLiteral("\\\""));
    return QLatin1Char('"') + value + QLatin1Char('"');
}

QString resolved(const QString &value, const QString &fallback)
{
    return value.isEmpty() ? fallback : value;
}

QString includePath(QString line)
{
    line = line.trimmed();
    if (line.startsWith(QLatin1Char('#')) || !line.startsWith(QStringLiteral("Include"), Qt::CaseInsensitive)) {
        return {};
    }
    QString candidate = line.mid(7).trimmed();
    if (candidate.size() >= 2 && candidate.front() == QLatin1Char('"') && candidate.back() == QLatin1Char('"')) {
        candidate = candidate.mid(1, candidate.size() - 2);
    }
    return candidate;
}

bool referencesPath(const QString &line, const QString &target)
{
    const QString candidate = includePath(line);
    return !candidate.isEmpty() && QFileInfo(candidate).absoluteFilePath() == target;
}
}

QString ManagedSshConfig::defaultPath()
{
    return QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation) + QStringLiteral("/waypane/ssh/config");
}

QString ManagedSshConfig::userConfigPath()
{
    return QDir::homePath() + QStringLiteral("/.ssh/config");
}

QString ManagedSshConfig::aliasFor(const ConnectionProfile &profile)
{
    if (!profile.sshConfigAlias.isEmpty()) {
        return profile.sshConfigAlias;
    }
    QString id = profile.id;
    id.replace(QRegularExpression(QStringLiteral("[^A-Za-z0-9_-]")), QStringLiteral("-"));
    return QStringLiteral("waypane-") + id;
}

QString ManagedSshConfig::render(const QList<ConnectionProfile> &profiles)
{
    QString result = QStringLiteral("# Generated by Waypane. Edit profiles in Waypane, not this file.\n\n");
    for (const ConnectionProfile &profile : profiles) {
        if (profile.id.isEmpty()) {
            continue;
        }
        result += QStringLiteral("Host %1\n").arg(aliasFor(profile));
        result += QStringLiteral("    HostName %1\n").arg(profile.host);
        result += QStringLiteral("    Port %1\n").arg(profile.port);
        if (!profile.username.isEmpty()) {
            result += QStringLiteral("    User %1\n").arg(profile.username);
        }
        if (!profile.identityFile.isEmpty()) {
            result += QStringLiteral("    IdentityFile %1\n").arg(quoted(profile.identityFile));
            result += QStringLiteral("    IdentitiesOnly yes\n");
        }
        if (profile.authentication == QStringLiteral("password")) {
            result += QStringLiteral("    PreferredAuthentications password,keyboard-interactive\n");
            result += QStringLiteral("    PubkeyAuthentication no\n");
        }
        if (!profile.jumpHosts.isEmpty()) {
            result += QStringLiteral("    ProxyJump %1\n").arg(profile.jumpHosts.join(QLatin1Char(',')));
        }
        for (const QString &forward : profile.localForwards) {
            result += QStringLiteral("    LocalForward %1\n").arg(forward);
        }
        for (const QString &forward : profile.remoteForwards) {
            result += QStringLiteral("    RemoteForward %1\n").arg(forward);
        }
        for (const QString &forward : profile.dynamicForwards) {
            result += QStringLiteral("    DynamicForward %1\n").arg(forward);
        }
        if (profile.agentForwarding) {
            result += QStringLiteral("    ForwardAgent yes\n");
        }
        if (profile.compression) {
            result += QStringLiteral("    Compression yes\n");
        }
        if (profile.legacyCompatibility) {
            result += QStringLiteral("    HostKeyAlgorithms +ssh-rsa\n");
            result += QStringLiteral("    PubkeyAcceptedAlgorithms +ssh-rsa\n");
            result += QStringLiteral("    KexAlgorithms +diffie-hellman-group1-sha1,diffie-hellman-group14-sha1\n");
            result += QStringLiteral("    Ciphers +aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc\n");
            result += QStringLiteral("    MACs +hmac-sha1,hmac-sha1-96\n");
        }
        if (profile.hostKeyPolicy != QStringLiteral("ask")) {
            result += QStringLiteral("    StrictHostKeyChecking %1\n").arg(profile.hostKeyPolicy);
        }
        if (!profile.knownHostsFile.isEmpty()) {
            result += QStringLiteral("    UserKnownHostsFile %1\n").arg(quoted(profile.knownHostsFile));
        }
        result += QLatin1Char('\n');
    }
    return result;
}

bool ManagedSshConfig::hasInclude(const QString &userConfig, const QString &managedConfig)
{
    QFile file(resolved(userConfig, userConfigPath()));
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return false;
    }
    const QString target = QFileInfo(resolved(managedConfig, defaultPath())).absoluteFilePath();
    const QString text = QString::fromUtf8(file.readAll());
    const QStringList lines = text.split(QLatin1Char('\n'));
    for (const QString &line : lines) {
        if (referencesPath(line, target)) {
            return true;
        }
    }
    return false;
}

bool ManagedSshConfig::isIncluded(const QString &userConfig, const QString &managedConfig)
{
    QFile file(resolved(userConfig, userConfigPath()));
    if (!file.open(QIODevice::ReadOnly | QIODevice::Text)) {
        return false;
    }
    const QString target = QFileInfo(resolved(managedConfig, defaultPath())).absoluteFilePath();
    bool enteredHostBlock = false;
    const QStringList lines = QString::fromUtf8(file.readAll()).split(QLatin1Char('\n'));
    for (const QString &line : lines) {
        const QString trimmed = line.trimmed();
        if (!trimmed.startsWith(QLatin1Char('#'))
            && (trimmed.startsWith(QStringLiteral("Host "), Qt::CaseInsensitive)
                || trimmed.startsWith(QStringLiteral("Match "), Qt::CaseInsensitive))) {
            enteredHostBlock = true;
        }
        if (referencesPath(line, target)) {
            return !enteredHostBlock;
        }
    }
    return false;
}

bool ManagedSshConfig::installInclude(QString *error, const QString &userConfig, const QString &managedConfig)
{
    const QString userPath = resolved(userConfig, userConfigPath());
    const QString managedPath = QFileInfo(resolved(managedConfig, defaultPath())).absoluteFilePath();
    if (isIncluded(userPath, managedPath)) {
        return true;
    }

    const QFileInfo info(userPath);
    if (!QDir().mkpath(info.absolutePath())) {
        if (error) {
            *error = QStringLiteral("Could not create %1").arg(info.absolutePath());
        }
        return false;
    }
    QByteArray existing;
    QFile input(userPath);
    if (input.exists()) {
        if (!input.open(QIODevice::ReadOnly)) {
            if (error) {
                *error = input.errorString();
            }
            return false;
        }
        existing = input.readAll();
    }
    QStringList retained;
    const QString marker = QStringLiteral("# Waypane managed connection profiles");
    for (const QString &line : QString::fromUtf8(existing).split(QLatin1Char('\n'))) {
        if (line.trimmed() == marker || referencesPath(line, managedPath)) {
            continue;
        }
        retained.append(line);
    }
    while (!retained.isEmpty() && retained.first().trimmed().isEmpty()) {
        retained.removeFirst();
    }
    const QString body = retained.join(QLatin1Char('\n'));
    existing = (marker + QStringLiteral("\nInclude \"") + managedPath + QStringLiteral("\"\n\n") + body).toUtf8();
    if (!existing.endsWith('\n')) {
        existing += '\n';
    }

    QSaveFile output(userPath);
    if (!output.open(QIODevice::WriteOnly) || output.write(existing) != existing.size() || !output.commit()) {
        if (error) {
            *error = output.errorString();
        }
        return false;
    }
    QFile::setPermissions(userPath, QFileDevice::ReadOwner | QFileDevice::WriteOwner);
    return true;
}

bool ManagedSshConfig::write(const QList<ConnectionProfile> &profiles, QString *error, const QString &path)
{
    const QString outputPath = resolved(path, defaultPath());
    const QFileInfo info(outputPath);
    if (!QDir().mkpath(info.absolutePath())) {
        if (error) {
            *error = QStringLiteral("Could not create %1").arg(info.absolutePath());
        }
        return false;
    }
    QSaveFile output(outputPath);
    if (!output.open(QIODevice::WriteOnly | QIODevice::Text)) {
        if (error) {
            *error = output.errorString();
        }
        return false;
    }
    const QByteArray contents = render(profiles).toUtf8();
    if (output.write(contents) != contents.size() || !output.commit()) {
        if (error) {
            *error = output.errorString();
        }
        return false;
    }
    QFile::setPermissions(outputPath, QFileDevice::ReadOwner | QFileDevice::WriteOwner);
    return true;
}

}
